### ISSUE TITLE
Payment fee does not show up in confirmation email

### ISSUE THREAD

**Issue by peterjaap** [tig-nl/buckaroo-magento2#28] opened 2018-07-06 13:19 UTC
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

Running version 1.7.1 on Magento 2.2.3.

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)

An order is placed using Mister Cash, and we've configured a 99 cent payment fee for this payment method. This comes through in the order view in the backend;

![image](https://user-images.githubusercontent.com/431360/42380657-f481296c-812e-11e8-9778-afb1eca069fa.png)

But the confirmation email does not show this fee although the totals add up;

![image](https://user-images.githubusercontent.com/431360/42380672-fe841eb0-812e-11e8-839a-7268e7e92667.png)

We use a custom template set through the backend, but that part has not been changed;

`{{layout handle="sales_email_order_items" order=$order}}`

**Comment by jasperzeinstra** [comment] 2018-07-09 13:42
Thanks @peterjaap for creating this issue. I was also just running in to this issue. Would really like to see this in an updated version.

**Comment by tig-jeffreypeeters** [comment] 2018-07-10 09:45
Hi Peterjaap,

Thank you for your submission. I've just tried to reproduce your problem and I can see that the fee is indeed missing from the confirmation email. I've created a backlog item for you and I'll keep you posted on any progress we make on the issue.

Kind regards,

Jeffrey
TIG

**Comment by peterjaap** [comment] 2018-08-09 09:45
@tig-jeffreypeeters any idea when this will be picked up?

**Comment by tig-jeffreypeeters** [comment] 2018-08-09 14:09
Hey Peterjaap,

My apologies for not keeping you in the loop on this issue. The backlog item has been picked up and is currently going through our internal review so if everything goes well you'll see the fix in either the upcoming or the following release. 

Kind regards,

Jeffrey
TIG

**Comment by tig-jeffreypeeters** [comment] 2018-08-28 09:43
Hey @peterjaap,

I wanted to update you on the status of this issue. The fix is still in our internal review but will likely be added to the next release (v1.7.3). Due to it being a vacation period I currently don't have an exact estimate for when this version will be released but i'll make sure to let you know when I know more.

Kind regards,

Jeffrey
TIG

**Comment by peterjaap** [comment] 2018-10-23 17:36
@tig-jeffreypeeters so 1.7.4 then? Any schedule available?

**Comment by tig-robertgrundeken** [comment] 2018-12-04 18:05
We added in v1.8.0 stable:
https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.8.0

**Closed by tig-robertgrundeken** 2018-12-04 18:05 UTC
