### ISSUE TITLE
Processing the same order from success page and background push causes incorrect financial / order state 

### ISSUE THREAD

**Issue by esseremmerik** [tig-nl/buckaroo-magento2#30] opened 2018-08-21 13:59 UTC
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with the TIG Buckaroo Magento extension)
---

### Description of your *issue*, suggested solution and other information

There are 2 endpoints in Magento where a request from Buckaroo can be processed. 
1: checkout success (buckaroo/Controller/Redirect/Process.php)
2: /rest/V1/buckaroo/push (buckaroo/Model/Push.php)

Sometimes it happens that we receive a frontend success and background push at the same time. Both functions execute in a separate way, they don't know from each other that they are processing something for the same order. Because of this, it can happen that both processes are opening the same order document at the same time, "changing" it, and "save" it.

Because of this behaviour the process which has the last "save" action, is the one that is actually keeping the changes in the order table, the other mutation is lost.

This leads to the situation that we have orders which contains invoices and transactions, but have an "open" total due column. The order is "pending" as the "total due" is still open and the order is stuck into this state until we manually update the corresponding financial columns in the order document to push the order to the processing state.

Our suggested solution is to not mutate the order document on the checkout success page to prevent this from happening. I believe this part of the code can cause this issue.

`case $this->helper->getStatusCode('TIG_BUCKAROO_STATUSCODE_SUCCESS'):
            case $this->helper->getStatusCode('TIG_BUCKAROO_STATUSCODE_PENDING_PROCESSING'):
                if ($this->order->canInvoice()) {
                    // Set the 'Pending payment status' here
                    $pendingStatus = $this->orderStatusFactory->get(
                        $this->helper->getStatusCode('TIG_BUCKAROO_STATUSCODE_PENDING_PROCESSING'),
                        $this->order
                    );
                    if ($pendingStatus) {
                        $this->order->setStatus($pendingStatus);
                        $this->order->save();
                    }
                }`

Hope you can help sorting this out.

**Comment by tig-robertgrundeken** [comment] 2018-08-21 16:40
@esseremmerik Thank you for the clear description of the issue. We will put it on the backlog and discuss the impact with Buckaroo. 
Regards,
Robert

**Comment by pauluse** [comment] 2018-10-11 08:35
@tig-robertgrundeken Is there any update regarding this issue?

**Comment by tig-robertgrundeken** [comment] 2018-10-11 09:05
We tested with removing the code and didn't foresee any problems. Only for a delay because the Push has same functionality but can take up to 5 minutes. From contact with @esseremmerik we learned that removing this code didn't solve their issue. They additionally removed the sending the of confirmation email https://github.com/tig-nl/buckaroo-magento2/blob/v1.7.2/Controller/Redirect/Process.php#L191 . And they are testing now with that. 

@pauluse Do you have any flow how to reproduce this problem? Or more information on this topic? We can't reproduce it, also not a specific payment method. Because it happens "sometimes". Any help is welcome :)

**Comment by tig-robertgrundeken** [comment] 2018-10-29 12:30
@esseremmerik  I made [v1.7.4-RC1](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.7.4-RC1) available with the fix. Still RC though.

**Comment by tig-jaspersmits** [comment] 2019-01-30 09:59
Version 1.8 is available therefore I will close this issue.

Kind regards,

Jasper
TIG

**Closed by tig-jaspersmits** 2019-01-30 09:59 UTC
