### ISSUE TITLE
Multi Currencies - 2.2.6

### ISSUE THREAD

**Issue by tom-iweb** [tig-nl/buckaroo-magento2#39] opened 2018-10-31 11:53 UTC
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Setup Magento with Multiple allowed currencies (GBP and EUR in this case)
- Setup Buckaroo with the same allowed currencies (GBP and EUR in this case)
- Set Base Currency to GBP
- On the frontend add to basket and switch currency to EUR (Anything other than the base currency)
- Proceed through Buckaroo Credit Card Payment
- On Callback the order will have a 'Suspected Fraud' status

**Expected result**
- Order is the same status as if it had checked out in base currency

**Actual result (Please provide screenshots if applicable)**
- On Callback the order will have a 'Suspected Fraud' status

**Workaround (If available, otherwise just write "None")**
- None

**Comment by tig-jaspersmits** [comment] 2018-11-05 15:01
Hi @tom-iweb,

Thank you for submitting this. We just tested this and were able to reproduce it. A backlog item has been created for this and will be investigated further. We strive to resolve this in an upcoming update. Do you want me to add your e-mailaddress to our release notes page? This way you will get an update once a new version is released and you can check if this has been fixed in that new release.

Looking forward to your response.

Kind regards,

Jasper
TIG

**Comment by tom-iweb** [comment] 2018-11-05 20:41
@tig-jaspersmits if you could add my email that would be good so we get an update once this is released

Thanks
Tom

**Comment by tig-jaspersmits** [comment] 2018-11-06 08:40
Hi @tom-iweb,

Would love to do that, but i do need your mail address. ;)
You can also send me a mail on sd@tig.nl if you don't want to share it here on Github.

Kind regards,

Jasper
TIG

**Comment by tig-robertgrundeken** [comment] 2018-12-06 12:36
Hi @tom-iweb my colleague has done some research on this issue and it isn't easy to fix due to the way magento works. What happens is:

The problem occurs when the paid amount send by the Buckaroo Push in another currency then the base currency (e.g. send: EUR, base: GPB). Right before creating an invoice Magento does some checks involving the base currency (GPB). The amounts and the currencies are not matching is seen as "Fraud" and will update the order with "Suspect Fraud".

* We cannot (and definitely don't want to) change the way Magento handles this.
* We see according to the code that actually the best way to set this up is to create a new storeview for every currency. We understand this is not ideal, but this is what to code dictates to work well (e.g. Magento does checks on the base currencies instead of currency in the order)
* We rather not recalculate the received amount by the Buckaroo Push back to the base currency due to rounding errors or differences due to exchange rates.

We keep looking for a solution with Buckaroo, but we don't know how much time this will take to solve..

**Comment by tig-robertgrundeken** [comment] 2019-01-15 15:35
Hi @tom-iweb 

Conclusion from discussion with Buckaroo is that this will not be solved by the extension. You can "solve" this by:

- We see according to the code that actually the best way to set this up is to create a new storeview for every currency. This is what to code dictates to work well (e.g. Magento does checks on the base currencies instead of currency in the order)

**Closed by tig-robertgrundeken** 2019-01-15 15:35 UTC
